name: trace
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_sparkline: ^0.0.4
  shared_preferences: ^0.4.1
  path_provider: ^0.4.0
  flutter_circular_chart: ^0.0.3

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/cdt.png
    - assets/images/exp.png
    - assets/images/lun.png
    - assets/images/ppp.png
    - assets/images/tnb.png
    - assets/images/abt.png
    - assets/images/chips.png
    - assets/images/fair.png
    - assets/images/maid.png
    - assets/images/ppt.png
    - assets/images/tnc.png
    - assets/images/act.png
    - assets/images/cix.png
    - assets/images/fct.png
    - assets/images/mana.png
    - assets/images/prl.png
    - assets/images/tnt.png
    - assets/images/ada.png
    - assets/images/clam.png
    - assets/images/fil.png
    - assets/images/mcap.png
    - assets/images/pura.png
    - assets/images/trig.png
    - assets/images/adx.png
    - assets/images/cloak.png
    - assets/images/fldc.png
    - assets/images/mco.png
    - assets/images/qash.png
    - assets/images/trx.png
    - assets/images/ae.png
    - assets/images/cmt.png
    - assets/images/flo.png
    - assets/images/mda.png
    - assets/images/qiwi.png
    - assets/images/tzc.png
    - assets/images/agi.png
    - assets/images/cnd.png
    - assets/images/fsn.png
    - assets/images/mds.png
    - assets/images/qlc.png
    - assets/images/ubq.png
    - assets/images/agrs.png
    - assets/images/cnx.png
    - assets/images/ftc.png
    - assets/images/med.png
    - assets/images/qrl.png
    - assets/images/unity.png
    - assets/images/aion.png
    - assets/images/cny.png
    - assets/images/fuel.png
    - assets/images/miota.png
    - assets/images/qsp.png
    - assets/images/usd.png
    - assets/images/amb.png
    - assets/images/cob.png
    - assets/images/fun.png
    - assets/images/mkr.png
    - assets/images/qtum.png
    - assets/images/usdt.png
    - assets/images/amp.png
    - assets/images/cred.png
    - assets/images/game.png
    - assets/images/mln.png
    - assets/images/r.png
    - assets/images/utk.png
    - assets/images/ant.png
    - assets/images/crpt.png
    - assets/images/gas.png
    - assets/images/mnx.png
    - assets/images/rads.png
    - assets/images/ven.png
    - assets/images/appc.png
    - assets/images/cs.png
    - assets/images/gbp.png
    - assets/images/mod.png
    - assets/images/rcn.png
    - assets/images/veri.png
    - assets/images/ardr.png
    - assets/images/ctr.png
    - assets/images/gbx.png
    - assets/images/mona.png
    - assets/images/rdd.png
    - assets/images/via.png
    - assets/images/ark.png
    - assets/images/cvc.png
    - assets/images/gbyte.png
    - assets/images/mth.png
    - assets/images/rdn.png
    - assets/images/vib.png
    - assets/images/arn.png
    - assets/images/dash.png
    - assets/images/generic.png
    - assets/images/mtl.png
    - assets/images/rep.png
    - assets/images/vibe.png
    - assets/images/ary.png
    - assets/images/dat.png
    - assets/images/gno.png
    - assets/images/music.png
    - assets/images/req.png
    - assets/images/vivo.png
    - assets/images/ast.png
    - assets/images/data.png
    - assets/images/gnt.png
    - assets/images/mzc.png
    - assets/images/rhoc.png
    - assets/images/vrc.png
    - assets/images/atm.png
    - assets/images/dbc.png
    - assets/images/grc.png
    - assets/images/nano.png
    - assets/images/ric.png
    - assets/images/vtc.png
    - assets/images/auto.png
    - assets/images/dcn.png
    - assets/images/grs.png
    - assets/images/nas.png
    - assets/images/rise.png
    - assets/images/wabi.png
    - assets/images/bat.png
    - assets/images/dcr.png
    - assets/images/gto.png
    - assets/images/nav.png
    - assets/images/rlc.png
    - assets/images/waves.png
    - assets/images/bay.png
    - assets/images/dent.png
    - assets/images/gup.png
    - assets/images/ncash.png
    - assets/images/rpx.png
    - assets/images/wax.png
    - assets/images/bcc.png
    - assets/images/dew.png
    - assets/images/gvt.png
    - assets/images/ndz.png
    - assets/images/rub.png
    - assets/images/wgr.png
    - assets/images/bcd.png
    - assets/images/dgb.png
    - assets/images/gxs.png
    - assets/images/nebl.png
    - assets/images/rvn.png
    - assets/images/wings.png
    - assets/images/bch.png
    - assets/images/dgd.png
    - assets/images/hpb.png
    - assets/images/neo.png
    - assets/images/salt.png
    - assets/images/wpr.png
    - assets/images/bcn.png
    - assets/images/dlt.png
    - assets/images/hsr.png
    - assets/images/neos.png
    - assets/images/san.png
    - assets/images/wtc.png
    - assets/images/bco.png
    - assets/images/dnt.png
    - assets/images/html.png
    - assets/images/ngc.png
    - assets/images/sbd.png
    - assets/images/xas.png
    - assets/images/bcpt.png
    - assets/images/doge.png
    - assets/images/huc.png
    - assets/images/nlc2.png
    - assets/images/sberbank.png
    - assets/images/xbc.png
    - assets/images/bdl.png
    - assets/images/drgn.png
    - assets/images/hush.png
    - assets/images/nlg.png
    - assets/images/sc.png
    - assets/images/xby.png
    - assets/images/bela.png
    - assets/images/dta.png
    - assets/images/icn.png
    - assets/images/nmc.png
    - assets/images/sky.png
    - assets/images/xcp.png
    - assets/images/bix.png
    - assets/images/dtr.png
    - assets/images/icx.png
    - assets/images/nuls.png
    - assets/images/slr.png
    - assets/images/xdn.png
    - assets/images/blcn.png
    - assets/images/ebst.png
    - assets/images/ignis.png
    - assets/images/nxs.png
    - assets/images/sls.png
    - assets/images/xem.png
    - assets/images/blk.png
    - assets/images/edg.png
    - assets/images/ink.png
    - assets/images/nxt.png
    - assets/images/smart.png
    - assets/images/xlm.png
    - assets/images/block.png
    - assets/images/edo.png
    - assets/images/ins.png
    - assets/images/oax.png
    - assets/images/sngls.png
    - assets/images/xmg.png
    - assets/images/blz.png
    - assets/images/edoge.png
    - assets/images/ion.png
    - assets/images/omg.png
    - assets/images/snm.png
    - assets/images/xmr.png
    - assets/images/bnb.png
    - assets/images/elf.png
    - assets/images/iop.png
    - assets/images/omni.png
    - assets/images/snt.png
    - assets/images/xmy.png
    - assets/images/bnt.png
    - assets/images/elix.png
    - assets/images/iost.png
    - assets/images/ont.png
    - assets/images/spank.png
    - assets/images/xp.png
    - assets/images/bnty.png
    - assets/images/ella.png
    - assets/images/itc.png
    - assets/images/ost.png
    - assets/images/sphtx.png
    - assets/images/xpa.png
    - assets/images/bos.png
    - assets/images/emc.png
    - assets/images/jnt.png
    - assets/images/ox.png
    - assets/images/srn.png
    - assets/images/xpm.png
    - assets/images/bpt.png
    - assets/images/emc2.png
    - assets/images/jpy.png
    - assets/images/part.png
    - assets/images/start.png
    - assets/images/xrp.png
    - assets/images/bq.png
    - assets/images/eng.png
    - assets/images/kcs.png
    - assets/images/pasl.png
    - assets/images/steem.png
    - assets/images/xtz.png
    - assets/images/brd.png
    - assets/images/enj.png
    - assets/images/kin.png
    - assets/images/pay.png
    - assets/images/storj.png
    - assets/images/xuc.png
    - assets/images/btc.png
    - assets/images/eos.png
    - assets/images/kmd.png
    - assets/images/pink.png
    - assets/images/storm.png
    - assets/images/xvc.png
    - assets/images/btcd.png
    - assets/images/equa.png
    - assets/images/knc.png
    - assets/images/pirl.png
    - assets/images/strat.png
    - assets/images/xvg.png
    - assets/images/btcp.png
    - assets/images/etc.png
    - assets/images/krb.png
    - assets/images/pivx.png
    - assets/images/sub.png
    - assets/images/xzc.png
    - assets/images/btcz.png
    - assets/images/eth.png
    - assets/images/lbc.png
    - assets/images/plr.png
    - assets/images/sys.png
    - assets/images/yoyow.png
    - assets/images/btg.png
    - assets/images/ethos.png
    - assets/images/lend.png
    - assets/images/poa.png
    - assets/images/taas.png
    - assets/images/zcl.png
    - assets/images/btm.png
    - assets/images/etn.png
    - assets/images/link.png
    - assets/images/poe.png
    - assets/images/tau.png
    - assets/images/zec.png
    - assets/images/bts.png
    - assets/images/etp.png
    - assets/images/lkk.png
    - assets/images/poly.png
    - assets/images/tel.png
    - assets/images/zen.png
    - assets/images/btx.png
    - assets/images/eur.png
    - assets/images/lrc.png
    - assets/images/pot.png
    - assets/images/theta.png
    - assets/images/zil.png
    - assets/images/burst.png
    - assets/images/evx.png
    - assets/images/lsk.png
    - assets/images/powr.png
    - assets/images/tix.png
    - assets/images/zrx.png
    - assets/images/cdn.png
    - assets/images/exmo.png
    - assets/images/ltc.png
    - assets/images/ppc.png
    - assets/images/tkn.png