name: Trace
description: Cryptocurrency portfolio and market explorer.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.4.1
  path_provider: ^0.4.0
  quick_actions: ^0.2.1
  flutter_circular_chart: ^0.0.3
  url_launcher: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/